[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#8A2BE2"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
